---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.10.0.154/22"],
                "mac": "3e:59:e4:f7:43:09"
              },{
                "name":"multus-internal",
                "namespace": "network",
                "ips": ["10.2.0.154/22"],
                "mac": "3e:59:e4:f7:43:09"
              }]

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 8.0.0
            env:
              MATTER_SERVER__INSTANCE_NAME: matter-server
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host matter-server.greyrock.dev
              MATTER_SERVER__LOG_LEVEL: debug
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsUser: 0 # Must be run as root user
        runAsGroup: 0
        runAsNonRoot: false # Must be run as root user
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.3.0.137
        ports:
          ws:
            port: *port
            primary: true

    persistence:
      config:
        existingClaim: matter-server-data
        advancedMounts:
          matter-server:
            app:
              - path: /data

    route:
      app:
        hostnames:
          - *host
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]
