---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.10",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "10.10.0.1" }
            ]
          }
        },
        {
          "type": "sbr"
        },
        {
          "type": "tuning",
          "capabilities": {
            "mac": true
          },
          "sysctl": {
            "net.ipv6.conf.net1.accept_ra": "1",
            "net.ipv6.conf.net1.accept_ra_rt_info_max_plen": "128"
          }
        }
      ]
    }
