---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/monitoring.giantswarm.io/silence_v1alpha1.json
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: nas1-memory-usage
spec:
  matchers:
    - name: alertname
      value: KubeHpaMaxedOut
      isRegex: false
    - name: horizontalpodautoscaler
      value: keda-hpa-.*
      isRegex: true
