---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - dining-room-zigbee-adapter.greyrock.internal
        - game-room-zwave-controller.greyrock.internal
        # TODO: Uncomment when the device is available
        # - pikvm.greyrock.internal
---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - nas1.greyrock.internal:2049
        - nas2.greyrock.internal:2049
        # - nas3.greyrock.internal:2049
