---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      node-red:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 977
            runAsGroup: 988
            fsGroup: 988
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: docker.io/nodered/node-red
              tag: 4.1.0@sha256:da6ac47cce14ed8df7ceddc8a15c8f4c0a41e0836c4d6e68e7a6a82329305a6b
            env:
              NODE_RED_ENABLE_SAFE_MODE: "false"
            resources:
              requests:
                cpu: 25m
                memory: 384Mi
              limits:
                memory: 512Mi
                # probes:
                #   liveness:
                #     enabled: true
                #   readiness:
                #     enabled: true
                # resources:
                #   requests:
                #     cpu: 136m
                #     memory: 1024Mi
                #   limits:
                #     gpu.intel.com/i915: 1
                #     memory: 8192Mi

    service:
      app:
        ports:
          http:
            port: 1880

    persistence:
      config:
        existingClaim: node-red-config
        advancedMounts:
          node-red:
            app:
              - path: /data

    route:
      app:
        hostnames:
          - node-red.greyrock.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
