---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .esphome_wifi_ssid }}"
          wifi_pwd: "{{ .esphome_wifi_password }}"

          domain_devices: .greyrock.internal

          garage_door_andy_ratgdo_api_key: "{{ .esphome_garage_door_andy_ratgdo_api_key }}"
          garage_door_todd_ratgdo_api_key: "{{ .esphome_garage_door_todd_ratgdo_api_key }}"
          bluetooth_proxy_office_api_key: "{{ .esphome_bluetooth_proxy_office_api_key }}"
          bluetooth_proxy_gameroom_api_key: "{{ .esphome_bluetooth_proxy_gameroom_api_key }}"
          bluetooth_proxy_garage_api_key: "{{ .esphome_bluetooth_proxy_garage_api_key }}"
          hvac_dining_room_api_key: "{{ .esphome_hvac_dining_room_api_key }}"
          hvac_game_room_api_key: "{{ .esphome_hvac_game_room_api_key }}"
          hvac_kitchen_api_key: "{{ .esphome_hvac_kitchen_api_key }}"
          hvac_master_bedroom_api_key: "{{ .esphome_hvac_master_bedroom_api_key }}"
          hvac_office_api_key: "{{ .esphome_hvac_office_api_key }}"
          light_dining_room_ceiling_1_api_key: "{{ .esphome_light_dining_room_ceiling_1_api_key }}"
          light_dining_room_ceiling_2_api_key: "{{ .esphome_light_dining_room_ceiling_2_api_key }}"
          light_dining_room_ceiling_3_api_key: "{{ .esphome_light_dining_room_ceiling_3_api_key }}"
          light_dining_room_ceiling_4_api_key: "{{ .esphome_light_dining_room_ceiling_4_api_key }}"
          light_dining_room_ceiling_5_api_key: "{{ .esphome_light_dining_room_ceiling_5_api_key }}"
          light_downstairs_bathroom_sink_1_api_key: "{{ .esphome_light_downstairs_bathroom_sink_1_api_key }}"
          light_downstairs_bathroom_sink_2_api_key: "{{ .esphome_light_downstairs_bathroom_sink_2_api_key }}"
          light_downstairs_bathroom_sink_3_api_key: "{{ .esphome_light_downstairs_bathroom_sink_3_api_key }}"
          light_downstairs_bathroom_sink_4_api_key: "{{ .esphome_light_downstairs_bathroom_sink_4_api_key }}"
          light_downstairs_bathroom_sink_5_api_key: "{{ .esphome_light_downstairs_bathroom_sink_5_api_key }}"
          light_downstairs_bathroom_sink_6_api_key: "{{ .esphome_light_downstairs_bathroom_sink_6_api_key }}"
          light_upstairs_hallway_ceiling_api_key: "{{ .esphome_light_upstairs_hallway_ceiling_api_key }}"
          light_living_room_side_api_key: "{{ .esphome_light_living_room_side_api_key }}"
          light_office_ceiling_1_api_key: "{{ .esphome_light_office_ceiling_1_api_key }}"
          light_office_ceiling_2_api_key: "{{ .esphome_light_office_ceiling_2_api_key }}"
          light_office_ceiling_3_api_key: "{{ .esphome_light_office_ceiling_3_api_key }}"
          light_office_ceiling_4_api_key: "{{ .esphome_light_office_ceiling_4_api_key }}"
          light_office_lamp_api_key: "{{ .esphome_light_office_lamp_api_key }}"
          plug_master_bedroom_christmas_api_key: "{{ .esphome_plug_master_bedroom_christmas_api_key }}"
          plug_master_bedroom_fan_api_key: "{{ .esphome_plug_master_bedroom_fan_api_key }}"
          zwave_coordinator_api_key: "{{ .esphome_zwave_coordinator_api_key }}"
  dataFrom:
    - extract:
        key: esphome
      rewrite:
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: esphome
        property: github_deploy_key
