---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nas-nfs-rules
spec:
  groups:
    - name: nas-nfs.rules
      rules:
        - record: nfs_probe_all_success
          expr: |-
            sum(probe_success{instance=~"nas[1-3].greyrock.internal:2049"}) == bool 3
