---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js-ui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      zwave-js-ui:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 977
            runAsGroup: 988
            fsGroup: 988
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 10.6.1
            resources:
              requests:
                cpu: 30m
                memory: 100Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &httpPort 8091
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

    service:
      app:
        ports:
          http:
            primary: true
            port: *httpPort
          websocket:
            port: 3000

    persistence:
      data:
        existingClaim: zwave-js-ui-data
        advancedMounts:
          zwave-js-ui:
            app:
              - path: /usr/src/app/store

    route:
      app:
        hostnames:
          - zwave-js-ui.greyrock.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
