---
# yaml-language-server: $schema=https://k8s-schemas.greyrock.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname node-red
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/home-automation/node-red/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: multus-networks
      namespace: network
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: system
    - name: keda
      namespace: system
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: node-red-config
      VOLSYNC_CAPACITY: 5Gi
