---
originRequest:
  originServerName: ingress-ext.greyrock.dev

ingress:
  - hostname: greyrock.dev
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.greyrock.dev"
    service: *svc
  - service: http_status:404
