---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName home-ops

endpoint: https://k8s.greyrock.internal:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.10.6
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.33.3

additionalApiServerCertSans: &sans
  - k8s.greyrock.internal
  - &talosControlplaneVip 10.3.0.30
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: k8s1.greyrock.internal
    ipAddress: 10.3.0.31
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: SAMSUNG MZ1LB1T9HALS-00007
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:5a:bd"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:5a:bc"
        ignore: true
        # bond0
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            - hardwareAddr: "58:47:ca:77:5a:*"
              driver: i40e
          xmitHashPolicy: layer3+4
          miimon: 100
          lacpRate: fast
          updelay: 0
          downdelay: 0
        dhcp: true
        vip:
          ip: *talosControlplaneVip
        vlans:
          - &vlan10
            vlanId: 10
            mtu: 1500
            dhcp: false
            dhcpOptions:
              routeMetric: 4096
          - &vlan100
            vlanId: 100
            mtu: 1500
            dhcp: false
            dhcpOptions:
              routeMetric: 4096

  - hostname: k8s2.greyrock.internal
    ipAddress: 10.3.0.32
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: SAMSUNG MZ1LB1T9HALS-00007
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:5e:dc"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:5e:dd"
        ignore: true
        # bond0
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            - hardwareAddr: "58:47:ca:77:5e:*"
              driver: i40e
          xmitHashPolicy: layer3+4
          miimon: 100
          lacpRate: fast
          updelay: 0
          downdelay: 0
        dhcp: true
        vip:
          ip: *talosControlplaneVip
        vlans:
          - *vlan10
          - *vlan100

  - hostname: k8s3.greyrock.internal
    ipAddress: 10.3.0.33
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    installDiskSelector:
      model: SAMSUNG MZ1LB1T9HALS-00007
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:58:8c"
        ignore: true
        # Intel VPRO
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:58:8d"
        ignore: true
        # bond0
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            - hardwareAddr: "58:47:ca:77:58:*"
              driver: i40e
          xmitHashPolicy: layer3+4
          miimon: 100
          lacpRate: fast
          updelay: 0
          downdelay: 0
        dhcp: true
        vip:
          ip: *talosControlplaneVip
        vlans:
          - *vlan10
          - *vlan100

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m

  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/gasket-driver
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/thunderbolt

  patches:
    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false
              [plugins."io.containerd.cri.v1.runtime"]
                device_ownership_from_security_context = true

    # Disable search domain everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Mount openebs-hostpath in kubelet
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/mnt/extra
              type: bind
              source: /var/mnt/extra
              options:
                - rbind
                - rshared
                - rw

    # Configure kubelet
    - |-
      machine:
        kubelet:
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 10.3.0.0/24

    # Enable MutatingAdmissionPolicy
    - |-
      cluster:
        apiServer:
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1alpha1=true
            feature-gates: MutatingAdmissionPolicy=true

    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                plugins:
                  score:
                    disabled:
                      - name: ImageLocality
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 10.3.0.0/24

    # # Configure NFS mount options
    # - |
    #   machine:
    #     files:
    #       - op: overwrite
    #         path: /etc/nfsmount.conf
    #         permissions: 0o644
    #         content: |
    #           [ NFSMount_Global_Options ]
    #           nfsvers=4.2
    #           hard=True
    #           noatime=True
    #           nconnect=16

    # Configure static host entries
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 10.3.0.30
              aliases:
                - k8s.greyrock.internal

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: "8192"      # Watchdog
          fs.inotify.max_user_watches: "1048576"     # Watchdog
          net.core.rmem_max: "67108864"              # Cloudflared / QUIC
          net.core.wmem_max: "67108864"              # Cloudflared / QUIC
          net.ipv4.neigh.default.gc_thresh1: "4096"  # Prevent ARP cache overflows
          net.ipv4.neigh.default.gc_thresh2: "8192"  # Prevent ARP cache overflows
          net.ipv4.neigh.default.gc_thresh3: "16384" # Prevent ARP cache overflows
          net.ipv4.tcp_fastopen: "3"                 # Send and accept data in the opening SYN packet
          user.max_user_namespaces: "11255"          # User namespaces

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - actions-runner-system
              - system-upgrade
