---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "grey-rock-dev"
spec:
  secretName: "grey-rock-dev-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "greyrock.dev"
  dnsNames:
    - "greyrock.dev"
    - "*.greyrock.dev"
